"""Property-based test for face-presence evaluation (Property 4).

Uses Hypothesis for property-based testing. Tagged with the design property
it validates.
"""
import sys
sys.path.insert(0, '.')

from hypothesis import given, settings, assume
from hypothesis import strategies as st

from drc_stat_engine.stats.dice_models import evaluate_face_condition, VALID_FACES_BY_TYPE

# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

all_faces_ship = sorted(VALID_FACES_BY_TYPE["ship"])
all_faces_squad = sorted(VALID_FACES_BY_TYPE["squad"])
all_faces_combined = sorted(set(all_faces_ship) | set(all_faces_squad))

# Valid face strings sampled from all faces across both pool types
valid_faces = st.sampled_from(all_faces_combined)

# Value strings: generated by joining random subsets of valid face tokens with spaces
value_string_from_faces = st.lists(
    st.sampled_from(all_faces_combined), min_size=0, max_size=10
).map(lambda tokens: " ".join(tokens))

# Pairs of faces where one is a substring of the other but not equal.
# E.g. B_hit is a substring of B_hit+crit, R_hit is a substring of R_hit+hit.
SUBSTRING_PAIRS = []
for f1 in all_faces_combined:
    for f2 in all_faces_combined:
        if f1 != f2 and f1 in f2:
            SUBSTRING_PAIRS.append((f1, f2))

passed = 0
failed = 0
errors = []

# ---------------------------------------------------------------------------
# Property 4: Face-presence evaluation correctness
# Feature: add-set-die-and-pool-color, Property 4: Face-presence evaluation correctness
# **Validates: Requirements 4.2, 4.3**
# ---------------------------------------------------------------------------

prop4_pass = True
prop4_error = None

# --- Sub-property 4a: General iff-token-membership ---
try:
    @given(face=valid_faces, value_str=value_string_from_faces)
    @settings(max_examples=200)
    def test_prop4a_iff_token_membership(face, value_str):
        """evaluate_face_condition returns True iff the face appears as a
        space-separated token in value_str."""
        result = evaluate_face_condition(face, value_str)
        tokens = value_str.split(" ")
        expected = face in tokens
        assert result == expected, (
            f"evaluate_face_condition({face!r}, {value_str!r}) returned {result}, "
            f"expected {expected} (tokens={tokens})"
        )

    test_prop4a_iff_token_membership()
except Exception as e:
    prop4_pass = False
    prop4_error = str(e)

# --- Sub-property 4b: Face present as token → True ---
try:
    @given(
        face=valid_faces,
        other_tokens=st.lists(st.sampled_from(all_faces_combined), min_size=0, max_size=8),
        insert_pos=st.integers(min_value=0, max_value=9),
    )
    @settings(max_examples=200)
    def test_prop4b_face_present_returns_true(face, other_tokens, insert_pos):
        """When the face is explicitly included as a token, result must be True."""
        tokens = list(other_tokens)
        pos = min(insert_pos, len(tokens))
        tokens.insert(pos, face)
        value_str = " ".join(tokens)
        assert evaluate_face_condition(face, value_str) is True, (
            f"Expected True for face={face!r} in value_str={value_str!r}"
        )

    test_prop4b_face_present_returns_true()
except Exception as e:
    prop4_pass = False
    prop4_error = str(e)

# --- Sub-property 4c: Face NOT present as token → False ---
try:
    @given(
        face=valid_faces,
        other_tokens=st.lists(st.sampled_from(all_faces_combined), min_size=0, max_size=8),
    )
    @settings(max_examples=200)
    def test_prop4c_face_absent_returns_false(face, other_tokens):
        """When the face is not among the tokens, result must be False."""
        tokens = [t for t in other_tokens if t != face]
        value_str = " ".join(tokens)
        assert evaluate_face_condition(face, value_str) is False, (
            f"Expected False for face={face!r} in value_str={value_str!r}"
        )

    test_prop4c_face_absent_returns_false()
except Exception as e:
    prop4_pass = False
    prop4_error = str(e)

# --- Sub-property 4d: Substring but not full token → False ---
if SUBSTRING_PAIRS:
    try:
        @given(
            pair=st.sampled_from(SUBSTRING_PAIRS),
            other_tokens=st.lists(st.sampled_from(all_faces_combined), min_size=0, max_size=6),
        )
        @settings(max_examples=200)
        def test_prop4d_substring_not_token_returns_false(pair, other_tokens):
            """When a face is a substring of another token but not present as its
            own token, evaluate_face_condition must return False.
            E.g. face='B_hit' in value_str='B_hit+crit R_blank' → False."""
            short_face, long_face = pair
            # Build value string containing the long face but NOT the short face
            tokens = [t for t in other_tokens if t != short_face]
            tokens.append(long_face)
            value_str = " ".join(tokens)
            # Confirm the short face is a substring of value_str (the tricky case)
            assume(short_face in value_str)
            assert evaluate_face_condition(short_face, value_str) is False, (
                f"Expected False: face={short_face!r} is substring of "
                f"value_str={value_str!r} but not a full token"
            )

        test_prop4d_substring_not_token_returns_false()
    except Exception as e:
        prop4_pass = False
        prop4_error = str(e)

if prop4_pass:
    print("PASS: Property 4 — Face-presence evaluation correctness")
    passed += 1
else:
    print(f"FAIL: Property 4 — {prop4_error}")
    failed += 1
    errors.append(("Property 4", prop4_error))

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print(f"\n{'='*60}")
print(f"Results: {passed} passed, {failed} failed out of {passed + failed}")
if failed == 0:
    print("ALL PROPERTY TESTS PASSED")
else:
    print("SOME PROPERTY TESTS FAILED")
    for name, err in errors:
        print(f"  {name}: {err}")
